name: Publish
on:
  push:
    branches: [master]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Source code clone
        uses: actions/checkout@v4
      - name: Node.js 20 (LTS) setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies installation
        run: yarn ci
      - name: Coding standard check
        run: yarn lint:prod
      - name: Types integrity check
        run: yarn check:types
      - name: Source code build
        run: yarn build
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: vuejs-varese-website
          path: dist

  deploy:
    name: GitHub Pages deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v4
        with:
          name: vuejs-varese-website

      - name: GitHub Pages setup
        uses: actions/configure-pages@v4
      - name: Artifact upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - id: deployment
        name: GitHub Pages deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
